### ISSUE TITLE
WARN: Cannot find a UUID for your node.

### ISSUE THREAD

**Issue by tomqwu** [inspec/train#341] opened 2018-08-22 20:25 UTC
### Description
Getting the following from Google Kubernetes Engine containers when running `chef/inspec`
> same steps work on my local macos docker
```
WARN: Cannot find a UUID for your node.
```

### Train and Platform Version
gems/train-1.4.31

== Platform Details

Name:      gcp
Families:  cloud, api
Release:   google-api-client-v0.19.8

### Replication Case
```
[tests] Running shell script
+ GOOGLE_CREDENTIAL=gcloud.json inspec detect -t gcp://

== Platform Details

Name:      gcp
Families:  cloud, api
Release:   google-api-client-v0.19.8

[tests] Running shell script
+ GOOGLE_CREDENTIAL=gcloud.json inspec detect
== Platform Details

Name:      alpine
Families:  linux, unix, os
Release:   3.7.0
Arch:      x86_64

[Pipeline] sh
[tests] Running shell script
+ GOOGLE_CREDENTIAL=gcloud.json inspec exec
[2018-08-22T20:19:00+00:00] WARN: Cannot find a UUID for your node.

Test Summary: 0 successful, 0 failures, 0 skipped

```

```
[tests] Running shell script
+ GOOGLE_CREDENTIAL=**** inspec exec acceptance/gcp -t gcp://
/usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/helpers/os_common.rb:137:in `update': no implicit conversion of nil into String (TypeError)
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/helpers/os_common.rb:137:in `uuid_from_string'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/uuid.rb:19:in `find_or_create_uuid'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/platform.rb:45:in `uuid'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/platform.rb:52:in `[]'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/resources/platform.rb:41:in `[]'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:190:in `platform'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:72:in `stop'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:201:in `block in notify'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `each'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `notify'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:194:in `stop'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:167:in `block in finish'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:186:in `close_after'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:166:in `finish'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:76:in `report'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner_rspec.rb:77:in `run'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner.rb:132:in `run_tests'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner.rb:103:in `run'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/cli.rb:173:in `exec'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/inspec-2.2.64/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
```
### Possible Solutions

N/A
### Stacktrace

```
/usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/helpers/os_common.rb:137:in `update': no implicit conversion of nil into String (TypeError)
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/helpers/os_common.rb:137:in `uuid_from_string'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/detect/uuid.rb:19:in `find_or_create_uuid'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/platform.rb:45:in `uuid'
	from /usr/local/bundle/gems/train-1.4.31/lib/train/platforms/platform.rb:52:in `[]'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/resources/platform.rb:41:in `[]'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:190:in `platform'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/formatters/base.rb:72:in `stop'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:201:in `block in notify'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `each'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `notify'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:194:in `stop'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:167:in `block in finish'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:186:in `close_after'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:166:in `finish'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:76:in `report'
	from /usr/local/bundle/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner_rspec.rb:77:in `run'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner.rb:132:in `run_tests'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/runner.rb:103:in `run'
	from /usr/local/bundle/gems/inspec-2.2.64/lib/inspec/cli.rb:173:in `exec'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/inspec-2.2.64/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
```

**Comment by tomqwu** [comment] 2018-08-22 20:52
Interestingly, once I switched to `GOOGLE_APPLICATION_CREDENTIALS` then the problem goes away. I think the documentation around how to pass GCP credential is needed as I was only able to discover this by reading https://github.com/inspec/train/blob/6bad712aaf6b8399ee0a5c52c150ae054b47067c/lib/train/transports/gcp.rb

**Comment by zenspider** [comment] 2019-10-14 20:21
I think this is a duplicate of #333. Closing. I'm gonna open a new doco issue for the last comment.

**Closed by zenspider** 2019-10-14 20:21 UTC
Labels: Component/UUID Generation, Transport/GCP, Type: Bug
